spring:
    profiles:
    active: dev
---
server:
  port: 8003
#spring的配置
spring:
  application:
    profiles:
    active: dev
    name: springcloud-provider-dept

#Erueka配置
eureka:
  client:
    service-url:
      defaultZone: http://vindaboy7001.com:7001/eureka/,http://vindaboy7002.com:7002/eureka/
      #defaultZone :是源码里面默认访问eureka的注册服务器地址,这里拿过来就是设置成为自己需要放置的服务器地址
---
server:
  port: 8004
#spring的配置
spring:
  application:
    profiles:
    active: test
    name: springcloud-provider-dept

#Erueka配置
eureka:
  client:
    service-url:
      defaultZone: http://vindaboy7001.com:7001/eureka/,http://vindaboy7002.com:7002/eureka/
      #defaultZone :是源码里面默认访问eureka的注册服务器地址,这里拿过来就是设置成为自己需要放置的服务器地址